# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master_pre_stage ]
  pull_request:
    branches: [ master_pre_stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy scikit-image
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        # change to the tests directory
        cd $GITHUB_WORKSPACE/tests
        
        # prepare the directory structure
        if [ ! -d test_images ]; then mkdir test_images; fi
        if [ ! -d test_results ]; then mkdir test_results; fi
        cd ..        
        # Run the tests
        python3 -m unittest tests/test_align.py
        
